### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Legendmanj** [mineblock11/continue-button#18]
update the mod to the latest version which is to be 1.21 and also fix the error/thing that happens for the mod to only continue on the last minecraft world on the client rather than a server, if it isnt already there it would be more appropirate to make it so that the last played server can be logged on when using the continue button

Thank You

**Comment by StuffOfSonny** [comment]
workaround posted here:
https://github.com/IMB11/continue-button/issues/17#issue-2399296505

As for servers, I can confirm that the Continue button does in fact remember the last server you were on and can log you into it.

**Comment by Legendmanj** [comment]
> workaround posted here: [#17 (comment)](https://github.com/IMB11/continue-button/issues/17#issue-2399296505)
> 
> As for servers, I can confirm that the Continue button does in fact remember the last server you were on and can log you into it.

welp thanks for the info, the thing is that last time i checked the mod seemed to only take me to the world options but it has been fixed ig(👍 


i would like to know whether the 1.21 version is upcoming sooner/ the updates on how it is going!
(;

**Comment by venaminecraft** [comment]
Thank you @StuffOfSonny, it worked!
