### ISSUE TITLE
Multiplayer doesn't persist [1.20]

### ISSUE THREAD

**Issue by Dabbpool** [mineblock11/continue-button#2]
i have tried everything to get it to save my multiplayer server and it just resets the config to single player

**Comment by Alec-wastaken** [comment]
I have the same problem, could not find any fix

**Comment by IMB11** [comment]
Please ensure you're using 0.1.1

**Comment by Alec-wastaken** [comment]
I am using the Version 0.1.1 downloaded from modrinth 
![image](https://github.com/mineblock11/continue-button/assets/88460695/b39ed3ca-55b7-40b7-b417-53e8217c72a7)

**Comment by zndrmn** [comment]
Same issue here, Using 1.1.1+1.20 and the continue button only works for singleplayer worlds
The 1.19.3 version worked fine

![image](https://github.com/mineblock11/continue-button/assets/77690119/6d4759f2-c1ad-4680-a1bb-20fc2c4c5bba)

This is what shows after connecting to a server (it just opens the last opened singleplayer world)

![image](https://github.com/mineblock11/continue-button/assets/77690119/87570ee5-9c2f-4b9f-9c79-72d1dd6d7221)

**Comment by IMB11** [comment]
I will be debugging this on the weekend. I am really busy at the moment with my studies.

**Comment by IMB11** [comment]
Fixed.
