### ISSUE TITLE
[1.20.1] Issue with worlds with the same name

### ISSUE THREAD

**Issue by DeshiDesu** [mineblock11/continue-button#7]
The last played world is New World (1) but it instead joins New World

![image](https://github.com/mineblock11/continue-button/assets/120287925/86d5869f-e54a-4779-ba62-2ccad26a8e10)
![image](https://github.com/mineblock11/continue-button/assets/120287925/d54a6371-a2d3-4f0e-8aef-a972772683bd)

**Comment by Art34222** [comment]
As a temporary solution, change the name of the world in the game and enter / exit it.
